#!/usr/bin/env perl
use strict;
use warnings;
use Data::Printer;
use Getopt::Long;
use File::Slurp;
use Cwd;

my $cur_dir = getcwd() . '/';

my $link_dir = File::HomeDir->my_home . "/bin/";
GetOptions ("path=s"   => \$link_dir) or die("Error in command line arguments\n");

if (! $link_dir =~ m/\/$/) {
    $link_dir .= '/';
}


if (! -d $link_dir) {
    print "Invalid directory: $link_dir\n";
    exit(0);
}


my $files = [split(/\n/, `grep -l link-me * 2> /dev/null | grep -v lnscripts`)];

foreach my $f (@$files) {
    my $ln_path = $link_dir . $f;
    my $real_path = $cur_dir . $f;

    my $script = read_file($real_path);
    if ($script =~ m/link-me:\s*(?<name>[^\s]+)$/gism) {
        $ln_path = $link_dir . $+{name};
    }
    
    
    
    if (! -e $ln_path) {
        print "ln -s $real_path $ln_path\n";
        `ln -s $real_path $ln_path`;
    }   
}
